export default {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',

  SEND_IMAGE: 'SEND_IMAGE',

  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',

  STORE_POSTS: 'STORE_POSTS',
  STORE_STORIES: 'STORE_STORIES',

  FOLLOW: 'FOLLOW',
  UNFOLLOW: 'UNFOLLOW',
};
